### ISSUE TITLE
Bibliographic Citations

### ISSUE THREAD

**Issue by flapka** [LD4P/ArtFrame-RareMat#15]
I feel obliged to begin with the caveat that I may have misunderstood components of the recommendation, and if that's the case please don't hesitate to point it out! My confusion begins with use of the term "citing entity." In the recommendation, it seems to be used to refer to the bibliography etc. in question. But when I read CiTO ontology definitions, it seems the other way around: the "cited entity" is the one referred to fulfill various functions. Pardon my head-spinning. 

Modeling of citations has been a bogeyman for BSC -- in the context of RDA. See our (rejected) proposal in 2015: http://www.rda-rsc.org/6JSC/ALA/45 

I have concerns about the use of CiTO to make the kind of references we use in our cataloging. My thought is that if CiTO is at the heart of this model, then we should be able to see how the subproperties of cito:cites or cito:is_cited_by are appropriate for the kinds of references we make -- and that's where I'm having some trouble.

As noted in the ALA paper above, we refer to bibliographies (etc.) for one of three reasons (generally):

1. to support one or more pieces of metadata in our record
2. to apply the bibliography entry number as a sort of identifier for the resource described
3. to say that the bibliography provides additional information about the resource described 

In use case 1, the cited resource acts as metadata provenance. That is, my cataloging assertion is justified by a bibliography etc. This looks equivalent to CiTO's "cited as data source" (http://www.sparontologies.net/ontologies/cito/source.html#d4e146). In that case, it's the metadata (not the Work/Instance/Item) that is domain, right? Is this use case modeled in the recommendation (or is there an example of it)? Or is it out of scope, treated elsewhere?

Use case 2 (bibliography entry number as identifier for the resource) is a muddy one. There's a sort of isSameAs to this. Do any of the CiTO ontology properties fulfill this function? At a glance, I can't find it.

Use case 3 (bibliography etc. describes resource) is in some ways the simplest. It's tempting to think that cito:is_described_by (http://www.sparontologies.net/ontologies/cito/source.html#d4e893) would be appropriate, but it isn't (?). As I read it, we'd use that property when the bibliography etc. is the entity being described -- which isn't something we do as catalogers.

**Comment by deborahjleslie** [comment]
I echo Francis' concerns (insofar as I understand them). What seems to be missing is the concept that the cited resource contains a _description_ of the described resource. 

Is there any significance to the ordering of the classes? That bibPage precedes bibVolume, although in constructing a citation, a volume number will precede a page number?

**Comment by timathom** [comment]
I can try to address some of the issues raised by @flapka and @deborahjleslie. 

Of the use cases outlined by Francis, the RareMat model can accommodate use cases 2 and 3, but it cannot really support use case 1. Part of the problem is that we are dealing with two separate citations here. Use case 1 represents a cataloging activity: i.e., the cataloger _cites_ a reference source. Use cases 2 and 3, by contrast, can be effectively modeled as a citing activity of the reference source: the reference _cites_ a given item, etc.

None of our current models provides a robust way to represent cataloging activities (I believe Deborah has raised this issue elsewhere as well). Earlier versions of the bibliographic citation recommendation tried to move in that direction via the Web Annotation model, but that proposal was ultimately rejected (unfortunately, the agency of the cataloger is still not seen as something worth modeling, by and large).

To model Francis's use case 1, I think something like this would be needed (think of these as RDF triples in prose):

```
Cataloger _creates_ resource description.
Resource description _cites as source data_ some reference source.
```

This use case _could_ have been accommodated, albeit not as directly, using the [Web Annotation model](https://www.w3.org/TR/annotation-model/), but, again, that approach has been rejected.

For use cases 2 and 3, I think that CiTO is appropriate, although maybe it requires thinking about bib citations a little differently. Some of the earliest versions of this recommendation attempted to model use case 2 as a `bf:Identifer`, but that was seen as too much of a stretch, since the entry number seems more like a location pointer than a strict identifier. The current recommendation tries to structure this information as much as possible, parsing into distinct entities (e.g., Entry, Page, Volume). 

In the CiTO model, a Citation is a node that links a citing entity to a cited entity. We have essentially the same pattern with bib citations:

```
Some reference source [citing entity] _cites_ an item being cataloged [cited entity].
```

To the point of use case 3, the _cites_ property could easily be replaced by a more specific subproperty such as _cito:describes_/_cito:isDescribedBy_, so I don't see any conflict there.

**Comment by deborahjleslie** [comment]
Thanks, Tim. And thanks for bearing with me as I stumble my way into and around bibframe. As I wrote Jason, I think I understand the generation of catalogers who felt overwhelmed by MARC as I try to wrap my head around the coding and structure of bibframe and other namespaces. (Is that the right terminology? *Please* correct any terminologic misuse.)

**Comment by deborahjleslie** [comment]
I see a problem with the use cases, in that they are not only mutually exclusive, but usually combine all three reasons for bibliographical citation. Especially for #1 and #3, they fulfill exactly the same function of pointing to a description of the resource being described. 

Would it not be correct to consider that *cito:describes/cito:isDescribedBy* supports all three uses?

**Comment by timathom** [comment]
Yes, I think that, generally, _cito:describes/cito:isDescribedBy_ gives adequate support for the core use case, as I understand it. The issue of administrative metadata, and of how to say things about the provenance or source of a given cataloging description, is a larger issue that hasn't really been addressed to date.

**Comment by timathom** [comment]
@rjyounes @jak473 When we first formalized this recommendation, the CiTO ontology modeled citations as activities (cito:CitationActivity). The ontology has since been revised and now treats citations as a separate entity (cito:Citation). Would we want to revisit this and consider adopting the CiTO Citation class, rather than minting our own? 

See https://sparontologies.github.io/cito/current/cito.html#d4e1598

**Comment by rjyounes** [comment]
We are no longer using the cito predicates.
